// Generated by CoffeeScript 1.10.0
(function() {
  var Base, ScriptTags,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  ScriptTags = (function(superClass) {
    extend(ScriptTags, superClass);

    ScriptTags.prototype.slug = "script_tag";

    ScriptTags.prototype.prefix = "/script_tags";

    function ScriptTags(site) {
      ScriptTags.__super__.constructor.call(this, site);
    }

    return ScriptTags;

  })(Base);

  module.exports = ScriptTags;

}).call(this);
